import Head from 'next/head'
import Footer from '../components/footer'
import Header from '../components/header'

export default function Home() {
  return (
    <div id='body' className='flex flex-col min-h-screen'>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Apple</title>
      </Head>
      <Header />
      <main className='flex-auto'>

      </main>
      <hr />
      <Footer />
    </div>  
  )
}